config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :issues

  post 'issues/:id/assign' => 'issues#assign', as: :assign_issue

  root 'issues#index'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'json'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  has_many :issues

  def self.from_omniauth(auth)
    # print out github information for debugging
    # puts JSON.pretty_generate(auth)
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.nickname = auth.info.nickname
      user.auth = auth.credentials.token
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :assign]

  # GET /issues
  # GET /issues.json
  def index
    load_suggestions
    @current_user = current_user
    @issues = []
    repos = github_client.repositories
    # magical API batch consoldiation
    repos.each do |repo|
      if repo.open_issues_count != 0
        issue_data = github_client.list_issues("#{repo.owner.login}/#{repo.name}")
        issue_data.each do |collect| 
          collect.repo = repo.name
        end
        @issues.push(issue_data)
      end
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @current_user = current_user
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    respond_to do |format|
      # create with a nil referrer in the table
      existing_issue = Issue.where(:id => @issue.id).first_or_create(issue_params) do |issue|
        # puts issue.inspect
        format.html { redirect_to issue, notice: 'Beginning the referral process. '}
        format.json { render :show, status: :created, location: issue }
      end
      format.html { redirect_to existing_issue, notice: 'Beginning the referral process. '}
      format.json { render :show, status: :created, location: existing_issue }
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    # update referrer and notes (if any)
    data = get_form_data
    data['referrer'] = @issue.referrer ? ("#{@issue.referrer},#{data['referrer']}") : data['referrer']
    baseline_note = "<span class='label warning' style='margin-right: 5px'><strong>#{current_user.nickname}</strong></span>#{data['notes']}<br/>"
    data['notes'] = @issue.notes ? (@issue.notes + baseline_note) : baseline_note
    respond_to do |format|
      if @issue.update(data)
        format.html { redirect_to @issue, notice: 'New referrer successfully added.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /issues/1/assign
  def assign
    repo = "#{current_user.nickname}/#{issue_params['repo']}"
    # assigns issue to current user on original GitHub 
    github_client.update_issue(repo, issue_params['number'].to_i, :assignee => current_user.nickname)
    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Assigned issue to #{current_user.nickname} on GitHub" }
      format.json { render :show, status: :ok, location: @issue }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.permit(:id, :url, :title, :body, :created_at, :repo, :notes, :number, :updated_at, :referrer)
    end

    def get_form_data
      params.require(:issue).permit(:id, :url, :title, :body, :repo, :notes, :number, :created_at, :updated_at, :referrer)
    end

    def github_client
      authToken = current_user.auth
      client = Octokit::Client.new(:access_token => authToken)
      client
    end

    def username
      current_user.nickname
    end

    def load_suggestions
      begin
      # fancy active record queries to get issues that have been referred to you
      @suggested_issues = Issue.all.where('referrer like ?', "%#{current_user.nickname}%")
      rescue
        @suggested_issues = nil
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/_nav.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">GitHub Issue Manager</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="active"><a href="https://www.github.com/<%= @current_user.nickname %>">Visit GitHub Profile</a></li>
        <li class="has-dropdown">
          <a href="#">Options</a>
          <ul class="dropdown">
            <li class="active"><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="#"></a></li>
      </ul>
    </section>
  </nav>
</div>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<%= render 'nav' %>

<% if (notice && !notice.empty?) %>
<div data-alert class="alert-box success radius">
  <span style="color:#fff; font-size: 12px" id="notice"><%= notice %></span>
  <a href="#" class="close">&times;</a>
</div>
<% end %>

<h1>Explore GitHub Issues</h1>
<h4 class="subheader">This section shows you all the available open issues amongst the GitHub repositories that you, or organizations that you belong to, own. If you find an issue, <span data-tooltip aria-haspopup="true" class="has-tip" title="Referring will cause the issue to show up in the Suggested Issues section for that user.">refer</span> it to a friend on GitHub!</h4>

<table>
  <thead>
    <tr>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;">Repository</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;" width="80">Issue State</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;">Title</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;">Body</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;" width="115">URL</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;" width="115">Refer a friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |repo_issue| %>
      <% repo_issue.each do |issue| %>
        <tr>
          <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><%= issue.repo %></td>
          <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><span class="label warning small"><%= issue.state %></span></td>
          <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><%= issue.title %></td>
          <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px;font-variant: normal; font-weight: 500;"><%= issue.body %></td>
          <td ><a class="button small info" style="color:#fff; font-size: 10px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500; padding: 4px" href="<%= issue.html_url %>"><i class="fa fa-share-square-o"></i> View on GitHub</a></td>
          <td><%= link_to '<i class="fa fa-share-alt"></i> Refer a friend'.html_safe, issues_path(id: issue.id, url: issue.html_url, repo: issue.repo, title: issue.title, body: issue.body, number: issue.number, created_at: issue.created_at, updated_at: issue.updated_at), :method => :post, class: 'button small success', style: "font-size: 10px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500; padding: 4px;" %></td>
        </tr>
       <% end %>
    <% end %>
  </tbody>
</table>

<hr />

<h1>Issues you should check out!</h1>
<h4 class="subheader">This section shows you all the issues that other users think you might be interested in. Think issue curation.</h4>

<% unless @suggested_issues.empty?%>
<table>
  <thead>
    <tr>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;">Repository</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;">Title</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;">Body</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;" width="150">Notes from referrer(s)</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;" width="105">URL</th>
      <th style="font-size: 14px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;" width="105">Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggested_issues.each do |issue| %>
      <tr>
        <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><%= issue.repo %></td>
        <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><%= issue.title %></td>
        <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><%= issue.body %></td>
        <td style="font-size: 12px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500;"><%= issue.notes.html_safe %></td>
        <td style="font-size: 10px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500; padding: 4px;"><a class="button small" style="color:#fff" href="<%= issue.url %>">View on GitHub</a></td>
        <td><%= link_to '<i class="fa fa-github"></i> Assign Issue'.html_safe, assign_issue_path(id: issue.id, number: issue.number, url: issue.url, repo: issue.repo, title: issue.title, body: issue.body, created_at: issue.created_at, updated_at: issue.updated_at), :method => :post, class: 'button small success', style: "font-size: 10px;font-family: 'Open Sans'; font-style: normal; line-height: 20px; font-variant: normal; font-weight: 500; padding: 4px;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>Nobody's suggested any issues for you as yet... :(</p>
<% end %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<%= render 'nav' %>

<% if (notice && !notice.empty?) %>
<div data-alert class="alert-box success radius">
  <span style="color:#fff; font-size: 12px" id="notice"><%= notice %></span>
  <a href="#" class="close">&times;</a>
</div>
<% end %>

<h3>Issue Details</h3>

<div style="border: 1px solid #090909; padding: 2%">
  <table>
    <thead>
      <tr>
        <td width='120'>Key</td>
        <td>Value</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong><h6>GitHub Issue ID</strong></h6></td>
        <td><h6 class="subheader"><%= @issue.id %></h6></td>
      </tr>
      <tr>
        <td><strong><h6>GitHub Repository</strong></h6></td>
        <td><h6 class="subheader"><%= @issue.repo %></h6></td>
      </tr>
      <tr>
        <td><h6><strong>Web URL</strong><h6></td>
        <td><h6 class="subheader"><%= @issue.url %></h6></td>
      </tr>
      <tr>
        <td><h6><strong>Title</strong></h6></td>
        <td><h6 class="subheader"><%= @issue.title %></h6></td>
      </tr>
      <tr>
        <td><h6><strong>Content</strong></h6></td>
        <td><h6 class="subheader"><%= @issue.body %></h6></td>
      </tr>
    </tbody>
  </table>

<% unless (@issue.referrer.nil?) %>
  <table>
    <tbody>
      <tr>
        <td width="180" style="background: rgba(80,80,80,0.1)">
          <h4 style="text-align: left;">Users referred to</h4>
        </td>
        <td>
        <% @issue.referrer.split(',').uniq.each do |ref| %>
          <a class="label large info" style="font-size: 12px; text-align: left; display:inline-block; margin: 2px; 0" href="http://www.github.com/<%= ref %>"><%= ref %></a>
        <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

</div>

<h3>Refer a GitHub user</h3>
<p>
  <h4 class="subheader">Referring an issue adds the issue to the user's suggested issue container, allowing you to recommend issues to people you think are best qualified to work on them.</h4>

  <%= form_for(@issue) do |f| %>
    <div class="field">
      <%= f.label :referrer, style: 'font-size: 24px' %><br>
      <%= f.text_field :referrer, placeholder: 'Enter a GitHub username', value: '', autofocus: true, class: 'referrer_input', style: 'line-height:14px' %>
    </div>
    <div class="field">
      <%= f.label :notes, style: 'font-size: 24px' %><br>
      <%= f.text_area :notes, placeholder: 'Enter notes for the user here. Maybe a few lines on why they might find this issue interesting?', value: '', class: 'notes_input'%>
    </div>
    <div class="actions">
      <%= f.submit 'Refer issue!', class: 'button', style: 'font-size:16px' %>
    </div>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>GitHub Issue Manager</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= google_webfonts_init(:google => ['Open Sans']) %>
  </head>

  <body style="padding-left: 5%; padding-right: 5%; font-family: 'Open Sans'; font-style: normal; font-variant: normal; font-weight: 500; line-height: 26px;">

    <%= yield %>

  </body>
</html>